### ISSUE TITLE
Does this library protect against session fixation attacks?

### ISSUE THREAD

**Issue by xiaojunlu** [jasny/sso#126]
Does using this library protect against session fixation attacks? If not, how should I defend myself?

To prevent this kind of attack, my current system assigns the user a new session ID using **_session_regenerate_id(true)_** when the user successfully logs in (or for each X request). Now only he has a session ID, and the old (fixed) session ID is no longer valid.

**Comment by jasny** [comment]
**Partly**

I'm assuming that your auth lib takes care of generating a new session on login. As you state, you're already doing that. Do make sure that the session data is deleted (either manually or by `session_regenerate_id`).

Brokers might still try to use the old session since that cookie isn't invalidated on logout, which isn't allowed. The `GlobalSession` handler prevents a broker from resuming a deleted session. See [line 69-72](https://github.com/jasny/sso/blob/master/src/Server/GlobalSession.php#L69)

On the broker side you might want to gracefully catch this error and reattach with a new token. This isn't done in the demo.
