### ISSUE TITLE
[Broker Ajax] - Broker didn't use bearer authentication

### ISSUE THREAD

**Issue by abcprintf** [jasny/sso#137]
I tried debug and it has Bearer data but why server side still reply didn't use bearer authentication

![2021-07-21_8-59-41](https://user-images.githubusercontent.com/8300694/126418715-d706ec7e-381a-4c80-a9f1-505977ade7e3.png)

**Comment by jasny** [comment]
If you use a logger (like Monolog), you get more details about the error.

The `Server::getBearerToken()` method takes the `Authorization` header from a PSR-7 request when provided. Otherwise, it uses the `$_SERVER` superglobal. https://github.com/jasny/sso/blob/master/src/Server/Server.php#L122

I don't know exactly how you dumped the headers. But it doesn't match the method used by the `Server` class.
