### ISSUE TITLE
Implementing two Websites User Auth, as Master-Slave duo, using your SSO for authentification in Slave?

### ISSUE THREAD

**Issue by LuckyCyborg** [jasny/sso#19]
Hello,

I try to implement a Master-Slave solution, made from two websites which need a common sign-in method. In theory, the Users sign in into Master, where they have access to a Private Area after login, with diverse pages.

Also, there are available some Files for download and a (AJAX) WebChat (which use of course, the Website's Auth System to find the users & Co.).

My intention is to move those (private) Files and the WebChat engine on a secondary website, while they can be available only under Authentication. But, what I want is that Secondary Website to transparently authenticate and un-authenticate the Users, following the Master website.
In theory, when the User is authenticated in Master, it should be automatically authenticated in Slave, with the same credentials as Username, Real Name, etc. An that User have access to his Private Files and WebChat, like those are hosted in the Master, where he is logged in.

You are kind to offer some suggestions about how can this design can be  implemented using your SSO?

**Comment by jasny** [comment]
Either make master the SSO server and the slave an SSO broker, or move the authentication to a separate project which is the SSO server and make both an SSO broker. The first option is probably the best in your case.

When you create start a session, make sure to store the client IP address as 'client_addr'.

Next extend SsoServer and implement the abstract methods. You can use it as controller, so route /sso to it, or copy index.php from the server example.

Since you only have one broker you can implement `getBrokerInfo` as

```php
protected function getBrokerInfo($broker) {
   if ($broker !== 'foo_webchat') return;
   return ['id' => 'foo_webchat', 'secret' => 'randomstring'];
}
```

The other methods should be self explanatory.

Next try running a demo broker as

    export SSO_SERVER=http://www.your-website-here.com/sso SSO_BROKER_ID=foo_webchat SSO_BROKER_SECRET=randomstring; php -S localhost:9001 -t examples/broker/

Now you should be able to log into your website via http://localhost:9001 and get the user info. Also when you're already logged into your website, you should see the user info directly (without have to login again).

If you have more questions, please use http://www.stackoverflow.com
