### ISSUE TITLE
The broker session id isn't attached to a user session

### ISSUE THREAD

**Issue by jkalousek** [jasny/sso#48]
Hi,
After few hours I gave up and decide to ask for help...
When I try to login "The broker session id isn't attached to a user session" is returned every time.
When I first land on login page SSO token is generated under cookies, but after pressing "Log in" button, cookie disappears and error is returned. I tried both methods for broker (AJAX, non-AJAX), same error every time.
Could the problem be that both Broker and server are running on same machine with same IP and only different port (Broker 55556, Server 55557)?

Can you please point me in right direction where to possibly look for errors?

Thank You!

**Comment by jasny** [comment]
**First, make sure you're using v0.2.3. Older version use the client IP, which is known to give issues.**

When visiting the broker for the first time, it should be redirecting the user to the server with a token. There the server will attach and redirect you back to the broker (non-AJAX).

The connection is saved in a file using Desarolla2\Cache. Delete all the cache files and clear all cookie. Than visited the broker in order to connect. You should now have a single cache file in '/tmp'. If it's missing, attaching fails probably because the cache file couldn't be created.

The cache file name has the format `SSO-{broker id}-{token}-{hash}`. Check if the broker id and token match those send in the request.

If they do match, the hash might not match. In that case, the broker secret configured on the server is not the same as on the broker.
