### ISSUE TITLE
Session Cache grows until never

### ISSUE THREAD

**Issue by infabo** [jasny/sso#58]
As already mentioned at #13, there is no session GC. In my case, using the File-adapter, had a cache-folder containing millions of files (sadly I didn't do a count before cleanup). `find . -mtime +5 -exec rm {} \;` did at least run for 20 minutes - now I'm at 134806 files. So maybe at least 2,5 million files before.

https://github.com/desarrolla2/Cache/blob/master/src/Adapter/AbstractAdapter.php#L59

Not a single concrete adapter implements a clearCache logic.

Please don't close this issue, just because it is a "missing feature" in an external library.
Consider implementing a cleanup within the SSO-Server class or replace desaroll2/cache with another PHP-cache library.

**Comment by jasny** [comment]
There is [already an issue open for this with desarrolla2/cache](https://github.com/desarrolla2/Cache/issues/31). Please consider providing the project with a Pull Request. Personally I think a cron job is a much better job to remove these files.

Most adapters don't need to implement that method, since they support TTL.

If you want to use a different PHP-cache libary or your custom cache solution, you can do so easily by extending the class and overwriting `createCacheAdapter()`. You just need an object that implements `get(string $name)` and `set(string $name, mixed $data)`.

Alternatively, if you're creating 25000 temp files per day, consider using an alternative storage. Preferably one that support TTL out of the box like memcached.

In any case **no**, this is not a concern of the SSO library.

**Comment by infabo** [comment]
Nice writeup.

Like I already said: consider replacing the desarolla-cache library.
Desarolla cache seemed and seems unmaintained to me, so that's why I posted here ("implement cleanup or replace the lib").

No, I won't provide a PR to desarolla cache (unmaintained and I hate making PRs which are not going to be merged - ever). Going to replace the lib with something that actually works. Cleanup-cronjobs. What about placing the cache-file in /tmp (resides in RAM) and do a daily reboot? Great!

**Comment by jasny** [comment]
@infabo PRs will get merged. I shoot in PRs all the time.

Which other cache library are you thinking of?
