### ISSUE TITLE
SSO in existing site which has always login

### ISSUE THREAD

**Issue by wonderunited** [jasny/sso#67]
Hey Arnold,

thank you for this great SSO Implementation. Its very easy, secure and extendable.

I used it for this case:

I habe a wordpress site, and if it is logged in, other external sites must be also logged in.

So in that case I did the following on server side (wordpress)

```
$broker = new Jasny\SSO\Broker('http://www.xxxx.de/sso/server/', 'xxxx', 'xxxx');
$ssoServer = new MySSOServer();
$ssoServer->startUserSession();

if (is_user_logged_in()) {
    $ssoServer->setSessionData('sso_user', 'xxxx');
} else {
    $ssoServer->setSessionData('sso_user', null);
}
```

This snipped is called after wordpress logout/login as callback. 

It that a good aproach and correct?, because it works. I did not want to create a new login on wordpress and want to use the existing login. 

Best Regards 
Sven

**Comment by jasny** [comment]
It's a way of doing it. But since the user id is already in the session (thanks to WordPress), it's not the way I'd recommended.

Instead overwrite the `SsoServer` methods `login` and `logout` methods to call `wp_signon()` and `wp_logout()`. And overwrite `userInfo()` to return the user information from WordPress (calling `get_userdata()`).

Ignore the `setSessionData()` and `getSessionData()` methods (make them always throw an exception).

_I'm closing this ticket. Please ask questions on [StackOverflow](http://www.stackoverflow.com) and live the issue tracker for issues. Ping me on Twitter at [@ArnoldDaniels](http://twitter.com/ArnoldDaniels) if needed._
