### ISSUE TITLE
CAS compatibility

### ISSUE THREAD

**Issue by marvoh** [jasny/sso#69]
I want to implement this with a broker application that only supports CAS v3.0 or SAML v2.0. 

Do you think your package would be able to help with this?

**Comment by jasny** [comment]
You can't use it with SAML.

You might be able to use the SSO server with CAS, but not out of the box.

* You need to remove the option for attaching through any other means than redirect.
* The server needs to as for credentials when not logged in, rather than redirecting back to the client.
* The data communication between the broker and server need to be in CAS format.

In short, you can use this as starting point for a very simple CAS server implementation. But it's just that... a starting point.

**Comment by jasny** [comment]
We might make Jasny SSO (optionally) compatible with CAS.

Note that the CAS protocol doesn't would only allow attaching using redirects, making it not AJAX compatible.

**Comment by marvoh** [comment]
Okay. Thanks
